[package]
name = "actuator-rs"
version = "0.0.1"
edition = "2018"


[dependencies]
log = "0.4"
anyhow = "1.0.42"
thiserror = "1.0.26"
num_enum = "*"
<<<<<<< HEAD
regex = "1"
=======
>>>>>>> b83cc3e (wip)
once_cell = "1.8.0"

[dev-dependencies]
env_logger = "0.9.0"
