[package]
name = "actuator-rs"
version = "0.0.1"
edition = "2018"


[dependencies]
log = "0.4"
anyhow = "1.0.42"
thiserror = "1.0.26"
num_enum = "*"
regex = "1"
once_cell = "1.8.0"
substring = "1.4.5"
rand = "0.8.4"
uri-rs = "0.0.4"
fasthash = "0.4"
dashmap = "4.0.2"

[dev-dependencies]
env_logger = "0.9.0"
